services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini-erp-php
    volumes:
      # - ./public:/var/www/html
      # - ./app:/var/www/html/app
      # - ./config:/var/www/html/config
      # - ./vendor:/var/www/html/vendor
      # - ./composer.json:/var/www/html/composer.json
      - ../:/var/www/html
    # FALTOU A LINHA ABAIXO PARA PODER FUNCIONAR O XDEBUG NA APLICACAO
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - internal
    # working_dir e command: Já definido no Dockerfile
    # working_dir: /var/www/html 
    # command: bash -c "docker-php-ext-install pdo pdo_mysql && apache2-foreground"

  db:
    image: mysql:8
    container_name: mini-erp-mysql
    restart: always
    environment:
      MYSQL_DATABASE: mini_erp
      MYSQL_USER: erp
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_PASSWORD: toor
    volumes:
      - db_data:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - internal
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    container_name: mini-erp-adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - internal

networks:
  internal:
    driver: bridge
    
volumes:
  db_data:
